version: '3.8'

services:
  web:
    build: app
    restart: always
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - mynetwork
    command: /bin/sh -c "sleep 10 && nginx -g 'daemon off;'"

networks:
  mynetwork: