version: '3.8'

services:
  ubuntu:
    image: ubuntu:latest
    container_name: my_ubuntu
    command: sleep infinity
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    networks:
      - my_network
    ports:
      - "5432:5432"

networks:
  my_network:
    driver: bridge